#############################
#  Do not edit this file.   #
#  File managed by salt.    #
#############################
export HISTSIZE=1000000;
export HISTFILESIZE=1000000
export HISTTIMEFORMAT="%F %T "

source /etc/bash_completion.d/git