# Script to build new AMI, used by packer for testing.
#
# Usage:
# - Create new empty cloud9 environmentE
# - Execute this script to generate new AMI

echo -n "Username:"
read username
description="Generated by ${username} at $(date +%s)"

# Pre-download docker images
docker pull fpfis/fpfis-base
docker pull phpmyadmin/phpmyadmin
docker pull fpfis/solr5
docker pull djfarrelly/maildev

# Create image
aws ec2 create-image \
--name="aws-cloud9-packer-template-$(date +%s)" \
--instance-id="$(curl -s http://169.254.169.254/latest/meta-data/instance-id)" \
--description="$description"

