# ==============================================================================
# Pull request clone ===========================================================
# ==============================================================================
# Use plugin to checkout pull requests for caching issue:
# https://github.com/drone/drone/issues/2390
# ==============================================================================
clone:
  git:
    image: plugins/git:next
    when:
      event: [ push, pull_request, tag ]
  git:
    image: plugins/git
    when:
      event: [ deployment ]

# ==============================================================================
# Workspace location ===========================================================
# ==============================================================================
# Define the build path inside the container ( Here /test/cloud9 )
# ==============================================================================
workspace:
  base: /test
  path: cloud9

# ==============================================================================
# pipeline =====================================================================
# ==============================================================================
pipeline:
  test-default:
    group: test
    image: fpfis/drone-plugin-packer
    secrets: [ AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY ]
    commands:
      - packer build -var Version=${DRONE_BUILD_NUMBER} -var profile=default -var AWS_AKI=$AWS_ACCESS_KEY_ID -var AWS_SAK=$AWS_SECRET_ACCESS_KEY test/aws.json
    when:
      event: [ push , pull_request ]
      branch: [master]

  test-docker:
    group: test
    image: fpfis/drone-plugin-packer
    secrets: [ AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY ]
    commands:
      - packer build -var Version=${DRONE_BUILD_NUMBER} -var profile=docker -var AWS_AKI=$AWS_ACCESS_KEY_ID -var AWS_SAK=$AWS_SECRET_ACCESS_KEY test/aws.json
    when:
      event: [ push , pull_request ]
      branch: [master]

  test-lamp-56:
    group: test
    image: fpfis/drone-plugin-packer
    secrets: [ AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY ]
    commands:
      - packer build -var Version=${DRONE_BUILD_NUMBER} -var profile=lamp-56 -var AWS_AKI=$AWS_ACCESS_KEY_ID -var AWS_SAK=$AWS_SECRET_ACCESS_KEY test/aws.json
    when:
      event: [ push , pull_request ]
      branch: [master]

  test-lamp-71:
    group: test
    image: fpfis/drone-plugin-packer
    secrets: [ AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY ]
    commands:
      - packer build -var Version=${DRONE_BUILD_NUMBER} -var profile=lamp-71 -var AWS_AKI=$AWS_ACCESS_KEY_ID -var AWS_SAK=$AWS_SECRET_ACCESS_KEY test/aws.json
    when:
      event: [ push , pull_request ]
      branch: [master]
      
  test-lamp-72:
    group: test
    image: fpfis/drone-plugin-packer
    secrets: [ AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY ]
    commands:
      - packer build -var Version=${DRONE_BUILD_NUMBER} -var profile=lamp-72 -var AWS_AKI=$AWS_ACCESS_KEY_ID -var AWS_SAK=$AWS_SECRET_ACCESS_KEY test/aws.json
    when:
      event: [ push , pull_request ]
      branch: [master]

  test-lamp-73:
    group: test
    image: fpfis/drone-plugin-packer
    secrets: [ AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY ]
    commands:
      - packer build -var Version=${DRONE_BUILD_NUMBER} -var profile=lamp-73 -var AWS_AKI=$AWS_ACCESS_KEY_ID -var AWS_SAK=$AWS_SECRET_ACCESS_KEY test/aws.json
    when:
      event: [ push , pull_request ]
      branch: [master]

  test-lamp-multi-versions:
    group: test
    image: fpfis/drone-plugin-packer
    secrets: [ AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY ]
    commands:
      - packer build -var Version=${DRONE_BUILD_NUMBER} -var instance=medium -var profile=lamp-multi-versions -var AWS_AKI=$AWS_ACCESS_KEY_ID -var AWS_SAK=$AWS_SECRET_ACCESS_KEY test/aws.json
    when:
      event: [ push , pull_request ]
      branch: [master]

  test-webtools:
    group: test
    image: fpfis/drone-plugin-packer
    secrets: [ AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY ]
    commands:
      - packer build -var Version=${DRONE_BUILD_NUMBER} -var instance=medium -var profile=webtools -var AWS_AKI=$AWS_ACCESS_KEY_ID -var AWS_SAK=$AWS_SECRET_ACCESS_KEY test/aws.json
    when:
      event: [ push , pull_request ]
      branch: [master]

  create-deploy-production:
      image: fpfis/drone-plugin-github-deploy
      state: create
      deploy_environment: production
      secrets: [ github_api_token ]
      automerge: false
      when:
        event: [push]
        branch: [master]

  push-production:
      image: kroniak/ssh-client
      secrets: [ SALT_MASTER_IP, SALT_MASTER_KEY ]
      commands:
        - echo "$SALT_MASTER_KEY" > /deploy.key
        - chmod 600 /deploy.key
        - ssh -o StrictHostKeyChecking=no -i /deploy.key ec2-user@$SALT_MASTER_IP sudo git -C "/srv/cloud9/" pull
      when:
        event: deployment

event : [pull_request, push ]
branches: master
