#############################
#  Do not edit this file.   #
#  File managed by salt.    #
#############################
# COMPOSER co
alias co='composer'
alias coi='composer install'
alias cou='composer update'

{% for php_version in php_versions %}
alias composer{{ php_version }}="/usr/bin/php{{ php_version}} /usr/bin/composer"

# COMPOSER co
alias co{{ php_version }}="composer{{ php_version }}"
alias coi{{ php_version }}="composer{{ php_version }} install"
alias cou{{ php_version }}="composer{{ php_version }} update"

{% endfor %}