#############################
#  Do not edit this file.   #
#  File managed by salt.    #
#############################

export DOCKER_HOST_IP=$(curl -s http://169.254.169.254/latest/meta-data/local-ipv4)

### Aliases ###

alias cloud9CpDockerFileAll='cloud9CpDockerFile all'
alias cloud9CpDockerFileMin='cloud9CpDockerFile min'

### Functions ###

function cloud9CpDockerFile() {
  type='all'
  [ "$1" != "" ] && type="$1"
  echo -n "Refresh local docker-compose.yml file..."
  sudo salt-call state.apply docker.cloud9-files --out=quiet
  echo "Done !"
  echo -n "Copy docker-compose-${type}.yml file to current directory..."
  cp /home/ec2-user/environment/.c9/docker/docker-compose/docker-compose-${type}.yml ${PWD}/docker-compose.yml
  echo "Done !"
  echo -n "Ensure buil folder exist..."
  mkdir -p "build" 
  echo "Done !"
}
